### ISSUE TITLE
Uncraftable potion bug not applied/updated on latest curseforge build?

### ISSUE THREAD

**Issue by Thomas107500** [Darkhax-Minecraft/Thirsty-Bottles#11]
I am using the latest ThirstyBottles-1.12.2-1.1.4 and i can see that the uncraftable potion bug should be fixed but according to the closed ticket but i still get uncraftable potion when i right click water source, i decompiled the latest curseforge jar and i didnt see the updated code inside(maybe i was wrong?) so maybe it didnt get updated? or just me being silly and other mods are affecting this?

**Comment by Darkhax** [comment]
The latest version on Curse is 1.1.9 not 1.1.4. Could you try updating and see if you still have the issue?

**Comment by Thomas107500** [comment]
Yup fixed after downloading the 1.1.9 build, can't see the 1.1.9 build the first time for some reason, i knew it was me being silly :P Thanks anyway :D
