### ISSUE TITLE
Bottles aren't consuming top source

### ISSUE THREAD

**Issue by Amanda212** [Darkhax-Minecraft/Thirsty-Bottles#12]
When using an empty bottle on the top source it will fill from the source underneath even when that source is empty. Only other mod I have that should effect water is Water Control Extreme but it works fine with buckets so it seems to be something wrong with this mod. I am using version 1.12.2-2.0.1
![2020-10-19_19 55 00](https://user-images.githubusercontent.com/73146708/96527401-99f5d380-1245-11eb-8977-2f28ee8c43ea.png)
![2020-10-19_19 55 03](https://user-images.githubusercontent.com/73146708/96527417-9f531e00-1245-11eb-907e-aa367c191219.png)
![2020-10-19_19 55 20](https://user-images.githubusercontent.com/73146708/96527424-a37f3b80-1245-11eb-8094-bc4e1698247b.png)

**Comment by Darkhax** [comment]
This issue has been fixed for 1.18.2+, older versions are no longer maintained.
