### ISSUE TITLE
ThirstyBottles graphical issue.

### ISSUE THREAD

**Issue by Taknax** [Darkhax-Minecraft/Thirsty-Bottles#14]
ThirstyBottles causes a graphical issue by JEI. The bittles have weirt texture.

[https://www.pinterest.de/pin/835417799627582851](url)

**Comment by Darkhax** [comment]
This mod does not modify the bottles in any way, and does not even run on the client side. The image you posted looks like a render state leak.

**Comment by Taknax** [comment]
Ty for reply. Do you have advise how to fix render state leak.
