### ISSUE TITLE
[BUG] Deletes waterlogged blocks

### ISSUE THREAD

**Issue by ThatGravyBoat** [Darkhax-Minecraft/Thirsty-Bottles#17]
### Minecraft Version

1.20.4

### Mod Version

10.0.2

### Mod Loader

NeoForge

### What environment are you running the mod in?

Dedicated Server

### Issue Description

When you use a bottle on a water logged block it deletes the block from the world instead of removing the waterlogged state this is because of this line here just setting the block to air: <https://github.com/Darkhax-Minecraft/Thirsty-Bottles/blob/1.20.4/common/src/main/java/net/darkhax/thirstybottles/mixin/MixinBottleItem.java#L27>

**Comment by Darkhax** [comment]
Thanks for reporting this issue. Definitely a major oversight on my part lol 😅

**Comment by Darkhax** [comment]
Fixed in https://github.com/Darkhax-Minecraft/Thirsty-Bottles/commit/dd8298a75464855678004fdf55da43e6a32480fa
