### ISSUE TITLE
[FEEDBACK] Alex's mobs lava bottle compat

### ISSUE THREAD

**Issue by NotTohm** [Darkhax-Minecraft/Thirsty-Bottles#19]
### Minecraft Version

1.20.1

### Mod Loader

Forge

### Feedback

lava bottles now consume the lava block like w/ water

**Comment by Darkhax** [comment]
Thanks for the feature request. This would require injecting code into Alex's Mobs which is something I try to avoid. Mod code can change without notice so injecting new code is very fragile and greatly increases the risk of instability. I would recommend asking them to add a config option for this on their end instead.
