### ISSUE TITLE
[QUESTION] How can I extend this mods functionality to other mod added items?

### ISSUE THREAD

**Issue by aya7mii** [Darkhax-Minecraft/Thirsty-Bottles#21]
### Question

[this mod](https://modrinth.com/mod/thirst-was-taken/version/1.20.1-1.3.1) adds clay bowls for drinking water. I was wondering how I can make this mod apply to that too? Is it possible with something like KubeJS? I assume it also all depends on how similar the clay bowls are to minecraft's bottles.

**Comment by Darkhax** [comment]
Hello, unfortunately that is not directly possible. The logic of this mod is intertwined with the glass bottle item and other mods often use their own logic for picking up water. Your best bet would be to ask them if they could add a config option to mimic this behaviour.
