### ISSUE TITLE
Uncraftable Potion

### ISSUE THREAD

**Issue by ilvrak** [Darkhax-Minecraft/Thirsty-Bottles#3]
after clicking on water, bottle return 'water bottle' AND - 'Uncraftable Potion'.

ThirstyBottles-1.12.2-1.1.4

**Comment by Darkhax** [comment]
Hello, thank you for the report. What mod is the "Uncraftable Potion" from?

**Comment by ilvrak** [comment]
vanilla minecraft, after implementing new potion mechanics with changing water bottle to potion with NBT tag "liquid type minecraft:water". Uncraftable Potion is a placeholder for potion with empty tag.

https://minecraft.gamepedia.com/Potion#Uncraftable_Potion

**Comment by Darkhax** [comment]
I've updated the mod to apply the correct NBT data to the item. This should fix the issue and mod conflicts.
