### ISSUE TITLE
Bottles don't react fully as an bucket 

### ISSUE THREAD

**Issue by cyberpunkbln** [Darkhax-Minecraft/Thirsty-Bottles#4]
Hello,

when i have an water source that have directly under the source an solid block bottles react as an normal bucket and suck the water fully as source, but when i try to take water from an deeper water source the bottles don't suck an water source and i can duplicate water.

thx

**Comment by Darkhax** [comment]
I can't recreate this issue based on the information you have provided. This mod doesn't prevent water source blocks from duplicating, it just makes bottles remove the block, which when combined with other mods can have that effect.
